### ISSUE TITLE
missing git tags for npm release 0.1.0

### ISSUE THREAD

**Issue by jokeyrhyme** [hailocab/react-pure#1]
Great project. I actually just started doing exactly the same thing this weekend and thought to check for a pre-existing wheel. Right down the experimenting with Babel and ES6! :)

Just noticed that there isn't a git tag that matches the 0.1.0 release on npm. Any chance you can add this? I often like to look at and compare the code for npm releases, and git tags on GitHub allow me to do this without leaving the web browser.

Cheers!

**Comment by PaulLeCam** [comment]
No problem, here it is: https://github.com/hailocab/react-pure/releases

**Comment by jokeyrhyme** [comment]
Thanks!
