### ISSUE TITLE
duplicate content at beginning of each module in /lib

### ISSUE THREAD

**Issue by jokeyrhyme** [hailocab/react-pure#2]
Just looking at the code in /lib for the latest commit:
- https://github.com/hailocab/react-pure/blob/62b15682a5a467b0e59ad6241d2fe1a7b6b83043/lib/Button.js
- https://github.com/hailocab/react-pure/blob/62b15682a5a467b0e59ad6241d2fe1a7b6b83043/lib/Cell.js
- etc...

I've noticed that the following 3 variables seem to be defined in most of the module files:
```javascript
var _interopRequire = function (obj) { return obj && obj.__esModule ? obj["default"] : obj; };

var _objectWithoutProperties = function (obj, keys) { var target = {}; for (var i in obj) { if (keys.indexOf(i) >= 0) continue; if (!Object.prototype.hasOwnProperty.call(obj, i)) continue; target[i] = obj[i]; } return target; };

var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };
```

I'm guessing this is coming from Babel somewhere, because I can see your `require(...)` calls as expected.

Is there a Babel setting to have these helper functions modularised and de-duplicated? I'm using Browserify, and it's possible that these duplicates will waste some space in my build output. Every byte counts. :)

I just had a quick glance at Babel and I can't see where these declarations are coming from (although their unit tests expect them).

**Comment by PaulLeCam** [comment]
It's possible (see https://babeljs.io/docs/usage/external-helpers/), but I don't think it's a good idea in our case, as it would force users of the library to include Babel helpers themselves.

If you really want them out, I think the best option is to load the source files from your application and compile them along with your application.

**Comment by jokeyrhyme** [comment]
Yeah, I've had a play with this and I can't figure out how to tell Babel to stop putting them in, let alone how to compensate for them being in a separate file. This seems like something Babel should be doing for us.

I tried
```sh
babel --no-external-helpers
```
and the output is the same regardless.

I'm sure GZIP compression eliminates the extra duplicates in transit anyhow.

That said, even this small tailored set of helpers is a going to be unnecessary parsing and execution, even if they don't bloat the GZIPed download too much. They are 584 bytes which ends up being a huge chunk of each module.

- Button: total bytes = 1963, helpers = 30%
- Cell: total bytes = 1791, helpers = 33%
- Menu: total bytes = 2322, helpers = 25%
- Table: total bytes = 1694, helpers = 34%

I'm going to report this upstream.

**Comment by sebmck** [comment]
See the [runtime](https://babeljs.io/docs/usage/runtime/) optional transformer.

**Comment by PaulLeCam** [comment]
Sorry I forgot about this issue, is that solved for you @jokeyrhyme or is there something I can implement in the lib without breaking things?

**Comment by jokeyrhyme** [comment]
Actually, I've just started using Babel myself, so I can avoid this issue in my own projects by just directly requiring the src/ files. If they can be added npm package, that's probably enough for me for now.

**Comment by PaulLeCam** [comment]
OK, I just published v0.2.2 that includes the `src` folder, please let me know if that works for you.

**Comment by jokeyrhyme** [comment]
Hi, thanks for publishing that change.

I'm using [browserify](http://browserify.org/) with the [babelify](https://github.com/babel/babelify) transform. Babelify won't recursively transform dependencies in node_modules unless they themselves specify that this is likely to work.

So, if you could be so kind, it would be terrific if you could add the following to the top-level of your package.json:
```json
  "browserify": {
    "transform": [
      [
        "babelify", {
          "experimental": true
        }
      ]
    ]
  }
```

The other thing I noted is that you are using [Babel's `experimental` transforms](https://babeljs.io/docs/usage/transformers/#es7-experimental-), specifically it looks like the Object Spread feature.

According to [Babel's `experimental` notice](http://babeljs.io/docs/usage/experimental/):
> These proposals are subject to change so use with extreme caution. babel may update without warning in order to track spec changes. Please do not use them in production applications.

The neat thing is that your package.json can enable experimental mode just for your module, and my project can disable experimental mode. Babelify just turns it on when it encounters your module.

If you do end up dropping experimental mode (i.e. when Object Spread graduates to a specification), then it might be a good idea to remove the line from that JSON snippet.

**Comment by PaulLeCam** [comment]
Hi,

I don't think it's the proper way forward, as it forces the users of the lib to apply the browserify/babelify transform themselves.
I just had a quick look at the Babel runtime transformer, isn't it possible to use it in your app build to extract the duplicate declarations?

About the experimental flag, yes it's only used for Object spread, once it's included by default in Babel it would be removed from the lib.

**Comment by PaulLeCam** [comment]
I just published v0.2.3 using babel-runtime, I think it's the best option to avoid duplicate declarations without needing specific transforms outside the library, does that work for you?

**Comment by jokeyrhyme** [comment]
Adding the package.json stuff doesn't force anyone to do anything, unless they want to avoid the duplication by using the ES6 source files you provide. If they don't care about the duplication, then they don't have to do anything differently.

With v0.2.2 and the custom package.json inserted:

```shell
ls -la www/*.min.js
-rw-r--r-- 1 ron ron 268450 Mar 19 08:23 www/app.min.js
-rw-r--r-- 1 ron ron   1198 Mar 19 08:23 www/loader.min.js
```

After updating to v0.2.3, replaced `require('react-pure/src/Button')` with `require('react-pure/lib/Button')`, and doing nothing else (I'm not using the transform, as my code doesn't directly use the helpers):

```shell
-rw-r--r-- 1 ron ron 294888 Mar 19 08:24 www/app.min.js
-rw-r--r-- 1 ron ron   1198 Mar 19 08:24 www/loader.min.js
```

I did try this with the transform, and it isn't any different in size.

Oddly enough, with v0.2.2 and using "lib" instead of "src", with no transforms, I get the same sizes when using "src" with no transforms. Simply enabling the transforms (either in your library or in my project) seems to add nearly 30KB to the output size.

My project only uses Button, Menu and MenuItem, and the output include the React library and everything else your library and my project require.

I'm curious to know what these numbers are like for your projects that use react-pure.

Let's be scientific about this. :) I'm willing to accept that my original hypothesis about the duplication was completely wrong, or at least not worse than the alternatives.

**Comment by PaulLeCam** [comment]
I've never used browserify this way so I can't tell, but reading the documentation on [browser.transform in package.json](https://github.com/substack/node-browserify#browserifytransform) it seems to me the transforms are applied whatever the `require()`, I don't see any option to transform the files from src but not lib?

About the size of your minified files, I really think it's out of the scope of this lib.
Sure, there is some overhead using Babel, but to me it's really worth the added convenience.

**Comment by jokeyrhyme** [comment]
> About the size of your minified files, I really think it's out of the scope of this lib.
I agree. You should just do whatever makes it easier to maintain this project. I suspect this is something that will be addressed upstream and within the ecosystem.

> I don't see any option to transform the files from src but not lib?
Just directly `require()`ing the src files was working for me:
```javascript
var Button = require('react-pure/src/Button');
```

**Comment by trusktr** [comment]
@sebmck Now that it has all gone [404](http://babeljs.io/docs/usage/runtime/), what do we do to get rid of these duplicate helpers?

**Comment by trusktr** [comment]
Alright, so the `--external-helpers` option still works, but it only replaces the calls and doesn't import anything. For example, I'm running

```js
babel src --source-maps --external-helpers --out-dir . --modules common
```

and that results in files that look like this at the top:

```js
'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true
});

var _lowclass = require('lowclass');

var _lowclass2 = babelHelpers.interopRequireDefault(_lowclass);

var _Node = require('./Node');

var _Node2 = babelHelpers.interopRequireDefault(_Node);

var _utilitiesPrivates = require('../utilities/Privates');

var _utilitiesPrivates2 = babelHelpers.interopRequireDefault(_utilitiesPrivates);

var __ = new _utilitiesPrivates2['default']();
```

Note that these files don't `require('babel-runtime')` or anything like that, so, these files will error out when we try to run them. This is a library that I'm compiling, and it has no entry point. This means that I will have to tell my users to manually import babel-runtime (or whichever package it is), which I'd love to avoid doing.

Is there a way to make Babel add the import to each file, or something?

**Comment by sebmck** [comment]
Use the babel-plugin-external-helpers-2 plugin. Someone was squatting on the other one :/

**Comment by trusktr** [comment]
@sebmck Did you know you can email NPM support, and if you present a valid case, they can help you get ownership to it.

**Comment by trusktr** [comment]
@sebmck I gave it a shot, and it errored out:

```
> npm install babel-plugin-external-helpers-2 --save
npm WARN install Couldn't install optional dependency: Unsupported
motor.js@0.0.2 /home/trusktr/src/infamous+motor
`-- babel-plugin-external-helpers-2@6.0.2
  `-- babel-runtime@6.0.8


> ./node_modules/.bin/babel src --source-maps --plugins external-helpers --out-dir . --modules common
ReferenceError: Unknown plugin "external-helpers"
    at PluginManager.subnormaliseString (/home/trusktr/src/infamous+motor/node_modules/babel-core/lib/transformation/file/plugin-manager.js:147:13)
    at PluginManager.add (/home/trusktr/src/infamous+motor/node_modules/babel-core/lib/transformation/file/plugin-manager.js:190:40)
    at File.buildTransformers (/home/trusktr/src/infamous+motor/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/home/trusktr/src/infamous+motor/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/home/trusktr/src/infamous+motor/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Object.exports.transform (/home/trusktr/src/infamous+motor/node_modules/babel/lib/babel/util.js:40:22)
    at Object.exports.compile (/home/trusktr/src/infamous+motor/node_modules/babel/lib/babel/util.js:49:20)
    at write (/home/trusktr/src/infamous+motor/node_modules/babel/lib/babel/dir.js:19:21)
    at handleFile (/home/trusktr/src/infamous+motor/node_modules/babel/lib/babel/dir.js:40:7)
    at /home/trusktr/src/infamous+motor/node_modules/babel/lib/babel/dir.js:56:9
```

**Comment by trusktr** [comment]
Running `ack '\bexternal-helpers\b'` in node_modules doesn't reveal any indication that the plugin name "external-helpers" is defined anywhere: http://trusktr.io:7777/akudoqoxit
