### ISSUE TITLE
compatibility with Node.js 0.12.x

### ISSUE THREAD

**Issue by jokeyrhyme** [hailocab/react-pure#3]
Just something I noticed whilst working on a pull request for #2.

npm run-script test

> react-pure@0.1.0 test /home/ron/Projects/react-pure
> jest --coverage ./lib

Using Jest CLI v0.4.0
 PASS  lib/utils/__tests__/joinClasses.js (0.056s)
 FAIL  lib/__tests__/Menu.js
Error: Worker process exited before responding! exit code: null, exit signal: SIGSEGV
stderr:
  

A worker process has quit unexpectedly! This is bad news, shutting down now!

npm ERR! Linux 3.18.6-1-ARCH
npm ERR! argv "/home/ron/.nvm/versions/node/v0.12.0/bin/node" "/home/ron/.nvm/versions/node/v0.12.0/bin/npm" "run-script" "test"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! react-pure@0.1.0 test: `jest --coverage ./lib`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-pure@0.1.0 test script 'jest --coverage ./lib'.
npm ERR! This is most likely a problem with the react-pure package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jest --coverage ./lib
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-pure
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ron/Projects/react-pure/npm-debug.log

I don't get any problems at all if I switch back to Node.js 0.10.36.

**Comment by PaulLeCam** [comment]
Jest is not compatibles with node v0.12 yet: https://github.com/facebook/jest/issues/243
