### ISSUE TITLE
react-pure-menu - Possibility for collaboration

### ISSUE THREAD

**Issue by bebraw** [hailocab/react-pure#4]
Hi,

I setup a [small project](https://bebraw.github.io/react-pure-menu/) making it easier to deal with Pure menus. I am aware your library goes much further than this!

It might be cool to make `react-pure` sort of an umbrella project for smaller libraries like this. Just need to agree on common semantics and so on.

**EDIT:** I ended up doing another, [react-pure-button](https://bebraw.github.io/react-pure-button/).

**Comment by PaulLeCam** [comment]
Hi,
Sure, would be nice!

How would you see this going? Simple links in Readme files between the different projects or more like splitting this library into individual components?

**Comment by bebraw** [comment]
[lodash](https://github.com/lodash/) may be worth mimicking here. They have an organization, a main project (lodash/lodash) and repos for smaller bits. In our case we could end up with something like this:

* react-pure - Org
* react-pure/react-pure - Umbrella project. Maybe this would just expose all the smaller libs through a simple interface? Ie. just index.js + references. Then you get `require('react-pure').Menu` and so on
* react-pure/react-pure-<component> - Each component would have a smaller repo like this. Pure isn't big so we would probably end up with something like six of these.

We would have to agree on some basic design for individual libraries besides this. In the end it just comes down to toggling some classes based on flags. In some cases (dropdown menu) more code is required.

**Comment by PaulLeCam** [comment]
That all seems really overkill to me for such a small library... lodash doesn't have each module in a separate repository, it's just separating the library from the tools.
I don't see the value of such a separation to be honest. It could be interesting if it was the way Pure split it's own styles, but it's not the case, so anyways it requires to load the entire Pure stylesheet.

**Comment by bebraw** [comment]
Yeah, it's true it could get more complicated than necessary. :)

Maybe it's better if I go through my libs and do some PRs for `react-pure` to get things synced up? Primarily I would port the lib to Webpack based flow, set up linting, basic tests and so on.

**Comment by PaulLeCam** [comment]
Sure, please feel free to contribute!
